version: '2'
services:
    wattie:
        image: wattie:latest
        build:
            context: ./
            dockerfile: Dockerfile
            args:
              ***REMOVED***_PASSWORD: $***REMOVED***_PASSWORD
        environment:
            - FIREBASE_CERTIFICATE_LOCATION=/secrets/${FIREBASE_CERTIFICATE_NAME}
            - CELL_NUMBER='***REMOVED***'
            - MONITOR_FREQUENCY=10
            - TIMEOUT=30
            - AUTH_TOKEN=$AUTH_TOKEN
            - ELASTIC_APM_SERVICE_NAME=wattie-bot
            - ELASTIC_APM_SERVER_URL=***REMOVED***:8200
            - ENABLE_DEBUG=False
            - SLACK_HOOK_URL=***REMOVED***
            - PROCESS_NEW_USERS_PERIOD_HOURS=3 # new users will be processed every 3 hours
            - DELIVERY_WINDOW_HOURS_BEFORE_AND_AFTER=3 # i.e. delivery window time = 2*DELIVERY_WINDOW_HOURS_BEFORE_AND_AFTER
            - ***REMOVED***_PASSWORD=$***REMOVED***_PASSWORD
        volumes:
            - pip_cache:/root/.cache/pip
            - ./downloads:/app/downloads
            - ./logs:/app/logs
            - ./data:/app/data
            - ${FIREBASE_CERTIFICATE_PATH}:/secrets
        ports:
            - 8001:8001 # API
            - 5555:5555 # Flower: Celery admin
            - 5050:5050 # ptvsd debugging
        depends_on:
            - mongodb
            - hub
            - selenium-firefox
            - redis
        networks:
            - net
        logging:
          options:
            max-size: 50m
    redis:
        image: redis:4.0.5-alpine
        command: ["redis-server", "--appendonly", "yes"]
        hostname: redis
        networks:
          - net
        volumes:
          - redis_data:/data
        logging:
          options:
            max-size: 50m
    mongodb:
        image: mongo:latest
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        volumes:
            - mongodb:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null
        networks:
            - net
        logging:
          options:
            max-size: 50m
    hub:
        image: selenium/hub:3.12.0-cobalt
        ports:
            - 4444:4444
        tty: true
        networks:
            - net
        logging:
          options:
            max-size: 50m
    selenium-firefox:
        image: selenium/node-firefox-debug:3.12.0-cobalt
        ports:
            - 5900:5900 # VNC
        tty: true
        depends_on:
            - hub
        volumes:
            - /dev/shm:/dev/shm
            - ./downloads:/app/downloads
        environment:
            - HUB_HOST=hub
            - HUB_PORT_4444_TCP_ADDR=hub
            - HUB_PORT_4444_TCP_PORT=4444
            - VNC_NO_PASSWORD=true # Access through SSH rather than direct to VNC port
        networks:
            - net
        logging:
          options:
            max-size: 50m

volumes:
    mongodb:
    pip_cache:
    redis_data:

networks:
    net:
      driver: bridge