version: '2'
services:
    wattie: &wattie
        build: .
        image: debian/latest:wattie
        environment:
#            - wattie.env
            - FIREBASE_CERTIFICATE_LOCATION=/secrets/${FIREBASE_CERTIFICATE_NAME}
            - CELL_NUMBER='***REMOVED***'
            - MONITOR_FREQUENCY=10
            - TIMEOUT=30
            - AUTH_TOKEN=$AUTH_TOKEN
            #           - GRPC_SSL_CIPHER_SUITES='ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384'
            - ELASTIC_APM_SERVICE_NAME=wattie-bot
            - ELASTIC_APM_SERVER_URL=***REMOVED***:8200
            - NUM_WORKERS=10
        volumes:
            - pip_cache:/root/.cache/pip
            - ./downloads:/app/downloads
            - ./logs:/app/logs
            - ./data:/app/data
            - ${FIREBASE_CERTIFICATE_PATH}:/secrets
        ports:
            - 8001:8001
            - 5555:5555
        depends_on:
            - mongodb
            - hub
            - selenium-firefox
        networks:
            - net
    redis:
        image: redis:4.0.5-alpine
        command: ["redis-server", "--appendonly", "yes"]
        hostname: redis
        networks:
          - net
        volumes:
          - redis_data:/data
    mongodb:
        image: mongo:latest
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        volumes:
            - mongodb:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null
        networks:
            - net
    hub:
        image: selenium/hub:3.12.0-cobalt
        ports:
            - 4444:4444
        tty: true
        networks:
            - net
    selenium-firefox:
        build:
          context: ./
          dockerfile: Dockerfile.FirefoxNode
        ports:
            - 5900:5900
        tty: true
        depends_on:
            - hub
        volumes:
            - /dev/shm:/dev/shm
            - ./downloads:/app/downloads
        environment:
            - HUB_HOST=hub
            - HUB_PORT_4444_TCP_ADDR=hub
            - HUB_PORT_4444_TCP_PORT=4444
            - SELENIUM_VNC_PASSWORD=${SELENIUM_VNC_PASSWORD}
        networks:
            - net

volumes:
    mongodb:
    pip_cache:
    redis_data:

networks:
    net:
      driver: bridge